# Generated by Django 3.0.6 on 2020-06-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='uname',
            new_name='username',
        ),
    ]
