# Generated by Django 3.0.6 on 2020-10-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20200607_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('distance', models.CharField(max_length=8)),
                ('type', models.CharField(max_length=30)),
                ('d_time', models.TimeField()),
                ('a_time', models.TimeField()),
            ],
        ),
    ]
