# Generated by Django 3.0.6 on 2020-10-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_busdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='distance',
            field=models.IntegerField(max_length=8),
        ),
    ]
