# Generated by Django 3.0.6 on 2020-10-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20201014_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='available_seat',
            field=models.IntegerField(default=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='distance',
            field=models.IntegerField(),
        ),
    ]
