# Generated by Django 3.0.6 on 2020-10-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_auto_20201015_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Bookingdetail',
        ),
    ]
