# Generated by Django 3.0.6 on 2020-10-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_auto_20201015_1936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookingdetail',
            new_name='Book',
        ),
    ]
