# Generated by Django 3.0.6 on 2020-10-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_auto_20201015_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='time',
        ),
        migrations.RemoveField(
            model_name='book',
            name='userid',
        ),
    ]
